version: '3.6'
services:
  notebook:
    build: .
    image: ocampor/jupyter-notebook
    ports:
      - 8000:8000
    volumes:
      - '${DATA_PATH}:/home/rocampo/data'
      - './notebooks:/home/rocampo/docs'
    entrypoint:
      - /bin/bash
      - /home/entrypoint.sh
